#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<ctype.h>
#include"userIO.h"
#include"fileIO.h"
#include"team.h"
#include"bst.h"
#include"stack.h"
#include"hash.h"
int getArrSize(FILE*in){int size=0;char temp[MAX_CHARS];while(fgets(temp,MAX_CHARS,in)!=NULL)size++;fclose(in);return size*2;}void readInFile(DATA_HEAD*data){FILE*dataFile;COMPANY*companyNode;char filename[MAX_CHARS],tmpName[MAX_CHARS];char ch;int tmpRev,tmpProfit,tmpNumEmployee;int i=0,isDuplicate,len,size;do{printf("Please enter a filename[enter for default]:");fgets(filename,MAX_CHARS,stdin);if(filename[0]=='\n')strcpy(filename,default_file);else{len=strlen(filename);if(filename[len-1]=='\n'||filename[len-1]=='\r')filename[len-1]='\0';else while((ch=getchar())!='\n'&&ch!='\r');}dataFile=fopen(filename,"r");}while(!dataFile);data->pTree=createBST(myStringCompare);data->pStack=createStack();size=getArrSize(dataFile);dataFile=fopen(filename,"r");data->arraySize=size;data->count=0;data->pHash=(HASH*)malloc(sizeof(DATA_HEAD)*data->arraySize);for(i=0;i<data->arraySize;i++){data->pHash[i].status=0;data->pHash[i].numOfCollisions=0;data->pHash[i].numOfProbes=0;data->pHash[i].hashData=NULL;}while(fscanf(dataFile,"%[^,],%d,%d,%d[^\n]",tmpName,&tmpRev,&tmpProfit,&tmpNumEmployee)!=EOF){companyNode=(COMPANY*)malloc(sizeof(COMPANY));if(!companyNode)exit(1);companyNode->companyName=(char*)malloc(strlen(tmpName)+1);if(!(companyNode->companyName))exit(1);strcpy(companyNode->companyName,tmpName);companyNode->numberOfEmployees=tmpNumEmployee;companyNode->revenuePerBillion=tmpRev;companyNode->profitPerMillion=tmpProfit;isDuplicate=searchHash(data,tmpName,companyNode);if(isDuplicate==1)printf("ERROR:DUPLICATE DATA\n");else{insertHash(data,companyNode);insertBST(data->pTree,companyNode);data->count++;}}printf("\nNumber Of Data Records read in:%d\n\n",data->count);fclose(dataFile);}int myStringCompare(void*pcompany1,void*pcompany2){return strcasecmp(((COMPANY*)pcompany1)->companyName,((COMPANY*)pcompany2)->companyName);}void cleanupData(DATA_HEAD*data){destroyBST(data->pTree,freeBST);destroyStack(data->pStack);free(data->pHash);free(data);}void freeBST(void*companyData){free(((COMPANY*)companyData)->companyName);free((COMPANY*)companyData);}void saveToFile(DATA_HEAD*data){COMPANY*temp;FILE*outputFile;char filename[MAX_CHARS];int i,len;char ch;do{printf("Please enter a filename for output file[enter for default]:");fgets(filename,MAX_CHARS,stdin);if(filename[0]=='\n')strcpy(filename,"out.txt");else{len=strlen(filename);if(filename[len-1]=='\n'||filename[len-1]=='\r')filename[len-1]='\0';else while((ch=getchar())!='\n'&&ch!='\r');}outputFile=fopen(filename,"w");}while(!outputFile);printf("Writing to%s...\n",filename);for(i=0;i<data->arraySize;i++){if(data->pHash[i].status==1)fprintf(outputFile,"%s,%d,%d,%d\n",data->pHash[i].hashData->companyName,data->pHash[i].hashData->revenuePerBillion,data->pHash[i].hashData->profitPerMillion,data->pHash[i].hashData->numberOfEmployees);}while(!emptyStack(data->pStack)){temp=(COMPANY*)popStack(data->pStack);free(temp->companyName);free(temp);}data->pStack->count=0;data->pStack->top=NULL;fclose(outputFile);printf("\n");}
